#/*******************************************************
# Loui Zibdawi							A2 
#
# 0924538								Feb. 12th, 2017
#
# CIS 3490								
#********************************************************/
all: P11 P12 P21 P22

P11: P11.c
	gcc P11.c -o P11 -Wall -std=c99

P12: P12.c
	gcc P12.c -o P12 -Wall -std=c99

P21: P21.c
	gcc P21.c -o P21 -Wall -std=c99

P22: P22.c
	gcc P22.c -o P22 -Wall -std=c99

clean:
	rm P11 P12 P21 P22