all: P11 P12 P21 P22 P23

P11: P11.c
	gcc P11.c -Wall -o p11 -ansi -std=c99

P12: P12.c
	gcc P12.c -Wall -o p12 -ansi -std=c99

P21: P21.c
	gcc P21.c -Wall -o p21 -ansi -std=c99

P22: P22.c
	gcc P22.c -Wall -o p22 -ansi -std=c99

P23: P23.c
	gcc P23.c -Wall -o p23 -ansi -std=c99

clean:
	rm P11 P12 P21 P22 P23